// Generated by wxt
export {};
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext'];
  const IENV: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env',
  )['IENV'];
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern'];
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern'];
  const ReflyEnv: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env',
  )['ReflyEnv'];
  const browser: typeof import('wxt/browser')['browser'];
  const calcPopupPosition: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['calcPopupPosition'];
  const checkBrowserArc: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/browser',
  )['checkBrowserArc'];
  const cn: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/cn',
  )['cn'];
  const createIframeUi: typeof import('wxt/client')['createIframeUi'];
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi'];
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi'];
  const dayjsConfig: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/dayjsConfig',
  )['default'];
  const defineBackground: typeof import('wxt/sandbox')['defineBackground'];
  const defineConfig: typeof import('wxt')['defineConfig'];
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript'];
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript'];
  const delay: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/delay',
  )['delay'];
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser'];
  const getCSSVar: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['getCSSVar'];
  const getCookie: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/cookie',
  )['getCookie'];
  const getEnv: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env',
  )['getEnv'];
  const getExtensionVersion: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/version',
  )['getExtensionVersion'];
  const getPopupContainer: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['getPopupContainer'];
  const handleGetAndWatchValue: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-storage',
  )['handleGetAndWatchValue'];
  const isMobileScreen: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['isMobileScreen'];
  const logger: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/logger',
  )['logger'];
  const mapDefaultLocale: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/locale',
  )['mapDefaultLocale'];
  const reflyEnv: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env',
  )['reflyEnv'];
  const retryify: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/retry',
  )['retryify'];
  const saveMockedResource: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/save-mocked-resource',
  )['saveMockedResource'];
  const scrollToBottom: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['scrollToBottom'];
  const scrollToTop: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/ui',
  )['scrollToTop'];
  const storage: typeof import('wxt/storage')['storage'];
  const useBindCommands: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-bind-commands',
  )['useBindCommands'];
  const useCountDown: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-count-down',
  )['useCountDown'];
  const useExtensionMessage: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-extension-message',
  )['useExtensionMessage'];
  const useGetUserSettings: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-get-user-settings',
  )['useGetUserSettings'];
  const useMockInAppResource: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-mock-in-app-resource',
  )['useMockInAppResource'];
  const useProcessLoginNotify: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-process-login-notify',
  )['useProcessLoginNotify'];
  const useRegisterMouseEvent: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-register-mouse-event',
  )['useRegisterMouseEvent'];
  const useSaveCurrentWeblinkAsResource: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-save-resource',
  )['useSaveCurrentWeblinkAsResource'];
  const useSaveSelectedContent: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-save-selected-content',
  )['useSaveSelectedContent'];
  const useSetContainerDimension: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-set-container-dimension',
  )['useSetContainerDimension'];
  const useStorage: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-storage',
  )['useStorage'];
  const useStoreWeblink: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-store-weblink',
  )['useStoreWeblink'];
  const useSwitchTheme: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-switch-theme',
  )['useSwitchTheme'];
  const useWatchStorage: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-storage',
  )['useWatchStorage'];
  const useWebLinkIndexed: typeof import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-weblink-indexed',
  )['useWebLinkIndexed'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { StorageLocation } from '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-storage';
  import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/hooks/use-storage'
  );
  // @ts-ignore
  export type {
    IENV,
    ReflyEnv,
  } from '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env';
  import(
    '/Users/songyuan/Documents/projects/lab/zhipu/AGENT/平台类/自动生成workflow/refly-main/refly/apps/extension/src/utils/env'
  );
}
