// Generated by wxt
import 'wxt/browser';

declare module 'wxt/browser' {
  export type PublicPath =
    | '/_locales/en/messages.json'
    | '/_locales/en_AU/messages.json'
    | '/_locales/en_GB/messages.json'
    | '/_locales/en_US/messages.json'
    | '/_locales/zh_CN/messages.json'
    | '/_locales/zh_TW/messages.json'
    | '/background.js'
    | '/content-scripts/contentSelector-csui.js'
    | '/content-scripts/floatingSphere-csui.js'
    | '/content-scripts/main-csui.js'
    | '/content-scripts/utils-csui.js'
    | '/icon/128.png'
    | '/icon/16.png'
    | '/icon/32.png'
    | '/icon/48.png'
    | '/icon/64.png'
    | '/popup.html';
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>;
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
